### PR TITLE
Make PDF objects public to allow access to pages

### PR DESCRIPTION
**Pull request by ThomasTJdev**
This PR sets `pages*: seq[Page]` and `curPage*: Page` as public. The purpose is to allow the user to navigate and access between the individual pages at any time.

While creating pages I need to be able to go back to a specific page and add text and images. This can be done easily when access to the `pages` and `curPage` is available.

The demo includes the statement `doc.setFont(xx)` - some of the other demo-files does not have this set, e.g. `basic_outline.pdf`, and on my machine there's no text on the pages (except for the first page).

### CODE REVIEW

**Comment by jangko** [comment]
I prefer public procs `gotoPage`, `gotoFirstPage`, `gotoLastPage`, `nextPage`, prevPage` or something similar rather than exposing implementation details.

**Comment by ThomasTJdev** [comment]
Would something like df5cd7e be better? Please let me know if you like some changes.

**Comment by ThomasTJdev** [comment]
Hi @jangko,
If you have any requests for changes, examples or documentation please let me.

**Comment by jangko** [comment]
ah sorry, I just forget to review this PR. it looks good to me.

**Pull request merged**
