### PR TITLE
Updated to support more images, added fallback to stb_image

### PR DESCRIPTION
**Pull request by windgo-inc**
Hello. Thank you so much for this library; I have found it extremely useful so far in generating compiled reports at work. I've added fallbacks to image library using stb_image if the current libs fail. This is useful for uJPEG especially which fails on numerous files that are okay, as well as added implicit support for Targa files. I understand if you aren't actively developing this project anymore, but I would like to help bring it up to date, as it is so useful! Thanks.

### CODE REVIEW

**Comment by jangko** [comment]
thank you, looks like the code is ok. it could be merged.
I actually working to add more interactive features...slowly, the Adobe PDF reference is such a dense material, really hard to digest the information.

I also have a request, if you don't mind, can you provide a link to those jpeg files? some decoder such as nimBMP and nimPNG are crafted to be resilient againts malformed or nonstandard input. while uJPEG only provide baseline decoder. stb_image could also employ the same tactics. but I cannot be sure without any sample. it really helpful if you could provide those files.

**Comment by windgo-inc** [comment]
Sure thing. I will have to go back and find my tests from where I discovered this. I am working on a lot at work, and this was part of a side project that I didn't document as well. I can indeed. It was a specific JPEG of our company's logo. I will try to find it for you on Monday.

**Comment by windgo-inc** [comment]
Hello again, Andri. Here are some of the images that were found to be breaking. The first image I found to be breaking was actually the JPEG output of stb_image at quality=50. I don't have time to do much more with this right now, but let me know if you see the "falling back" message I left in for when μJPEG fails.

https://github.com/windgo-inc/ujpeg-fail-imgs

**Comment by jangko** [comment]
thank you, I will take a look

**Comment by windgo-inc** [comment]
I also realized I should tell you this as well: I decided originally to replace the image decoding stuff you had entirely because it is cleaner to have one solution. However, I found that stb_image was unable to load the black and white or indexed PNGs correctly. It was because I didn't have too much time to spare on it that I accepted the fallback solution for my own purposes.

**Comment by jangko** [comment]
thank you for that information, and it was good you didn't replace it.
i had a plan for nimPDF future versions, that we will be able to choose which dependencies we want to include in the binary.

perhaps you can also report the bug you found to stb_image(the c++ one) team, and provide them with those indexed PNG

**Pull request merged**
